### ISSUE TITLE
你好，有没有监测摄像头网速的Api？没有找到好像

### ISSUE THREAD

**Issue by Goallying** [GWTimes/GWP2PSDK#5]

**Comment by wsxking** [comment]
网速会在下一个大版本加入。

**Comment by GWTimes** [comment]
/**
 @brief GWP2PVideoPlayerProtocol协议包含监控时的设备状态信息的回调,按需要选择性实现
 */
@protocol GWP2PVideoPlayerProtocol <GWP2PPlayerProtocol>

@optional

/**
 观看人数变化回调
 触发场景:
 1.呼叫设备后开始监控时
 2.观看人数变化时(其他监控者加入或者断开)
 3.高清-标清,高清-流畅,两种情况的分辨率互相切换时(标清-流畅切换不触发)
 
 @param currentNumber 当前观看人数
 */
- (void)p2pVideoPlayer:(GWP2PVideoPlayer *)player numberOfAudiencesChange:(NSUInteger)currentNumber;

/**
 监控网速发生改变，每秒回调一次
 @param player 播放器
 @param speed 网速
 */
- (void)p2pVideoPlayer:(GWP2PVideoPlayer *)player networkSpeedChanged:(NSInteger)speed;
/**
 远程录像(SD卡录像)状态发送改变
 @param parameters 参数 @"isRemoteRecording":@(BOOL),是否正在录像
                       @"hasSDCard":@(BOOL),是否有SD卡
                       @"isRecordFalse":@(BOOL),是否录制失败,可能SD卡损坏
 */
- (void)p2pVideoPlayer:(GWP2PVideoPlayer *)player remoteSDCardRecordStateChange:(NSDictionary *)parameters;
/**
 布防状态发生改变
 @param isDefenceOn 改变后的布防状态. YES:布防状态,NO:撤防状态
 */
- (void)p2pVideoPlayer:(GWP2PVideoPlayer *)player defenceStateChange:(BOOL)isDefenceOn;
@end
